version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=fennec
    networks:
      - freecodecamp
    restart: unless-stopped
  test-db:
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=fennec
    networks:
      - freecodecamp
    restart: unless-stopped
networks:
  freecodecamp:
